FROM registry.access.redhat.com/ubi9/ubi:9.6-1750786174@sha256:7a4818cdb8e0461d75d4bdfa42a355d3725bcc8cc0cc5d467021119d5962ce6b

ARG SYNC2JIRA_GIT_REPO=https://github.com/release-engineering/Sync2Jira.git
ARG SYNC2JIRA_GIT_REF=master
ARG SYNC2JIRA_VERSION=

LABEL \
    name="sync2jira-sync-page" \
    org.opencontainers.image.name="sync2jira-sync-page" \
    description="sync2jira application" \
    org.opencontainers.image.description="sync2jira application" \
    io.k8s.description="sync2jira application" \
    vendor="Red Hat, Inc." \
    org.opencontainers.image.vendor="Red Hat, Inc." \
    license="GPLv2+" \
    org.opencontainers.image.license="GPLv2+" \
    url="$SYNC2JIRA_GIT_REPO" \
    org.opencontainers.image.url="$SYNC2JIRA_GIT_REPO" \
    release="$SYNC2JIRA_GIT_REF" \
    com.redhat.component="null" \
    build-date="" \
    distribution-scope="public"

# Installing sync2jira dependencies
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN dnf -y install \
    git \
    python3-pip \
    krb5-devel \
    python-devel \
    fedora-messaging \
    gcc \
  && dnf -y clean all

USER root

# Copy in license file
RUN mkdir /licenses
COPY LICENSE /licenses/LICENSE

# Create Sync2Jira folder
RUN mkdir -p /usr/local/src/sync2jira

# Copy over our repo
COPY . /usr/local/src/sync2jira

# Install deps
RUN pip3 install -r /usr/local/src/sync2jira/requirements.txt

# Grab the latest pandoc binary
RUN python3 -c 'from pathlib import Path; import pypandoc; from pypandoc.pandoc_download import download_pandoc; download_pandoc(targetfolder=Path(pypandoc.get_pandoc_path()).parent)'

# Install Sync2Jira
RUN pip3 install --no-deps -v /usr/local/src/sync2jira

USER 1001

CMD ["python3", "/usr/local/src/sync2jira/sync-page/event-handler.py"]
