apiVersion: v1
kind: Template
metadata:
  name: sync2jira-template
  app: sync2jira
labels:
  app: sync2jira
parameters:
- name: CA_URL
  displayName: CA URL used for sync2jira
  required: true
- name: DEFAULT_SERVER
  displayName: Default server to use for mailing
  required: true
- name: DEFAULT_FROM
  displayName: Default from to use for mailing
  required: true
- name: USER
  displayName: JIRA username
  required: true
- name: CONFLUENCE_SPACE
  displayName: Confluence space
  required: true
- name: CONFLUENCE_PAGE_TITLE
  displayName: Confluence page title
  required: true
- name: CONFLUENCE_URL
  displayName: Confluence URL
  required: true
- name: CONFLUENCE_USERNAME
  displayName: Confluence username
  required: true
- name: INITILIZE
  displayName: True/False Initilize our repos on startup
  value: "1"
- name: IMAGE_URL
  displayName: Image URL:TAG to pull from
  value: "quay.io/redhat-aqe/sync2jira:latest"
- name: JIRA_PNT_PASS
  displayName: PNT password in base64
  requiered: true
- name: JIRA_OMEGAPRIME_PASS
  displayName: Omegaprime password in base64
  requiered: true
- name: SYNC2JIRA_CONFLUENCE_PASS
  displayName: Confluence password in base64
  requiered: true
- name: GITHUB_TOKEN
  displayName: GitHub token in base64
  requiered: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: sync2jira
    annotations:
      openshift.io/display-name: sync2jira
    name: sync2jira
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: ${IMAGE_URL}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: Secret
  metadata:
    name: sync2jira-secret
    labels:
      app: sync2jira
  data:
    jira_pnt_pass: |-
      ${JIRA_PNT_PASS}
    jira_omegaprime_pass: |-
      ${JIRA_OMEGAPRIME_PASS}
    sync2jira-confluence: |-
      ${SYNC2JIRA_CONFLUENCE_PASS}
    github_token: |-
      ${GITHUB_TOKEN}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: sync2jira
    labels:
      app: sync2jira
  spec:
    selector:
      service: sync2jira
    template:
      metadata:
        labels:
          app: sync2jira
          service: sync2jira
      spec:
        containers:
        - name: sync2jira-container
          image: sync2jira:stage
          imagePullPolicy: Always
          volumeMounts:
            - name: fedmsgd-volume
              mountPath: /etc/fedmsg.d
              readOnly: true
          env:
            - name: INITIALIZE
              value: ${INITILIZE}
            - name: CA_URL
              value: ${CA_URL}
            - name: DEFAULT_SERVER
              value: ${DEFAULT_SERVER}
            - name: DEFAULT_FROM
              value: ${DEFAULT_FROM}
            - name: USER
              value: ${USER}
            - name: SYNC2JIRA_PNTJIRA_PASS
              valueFrom:
                secretKeyRef:
                  key: jira_pnt_pass
                  name: sync2jira-secret
            - name: SYNC2JIRA_OMEGAPRIME_PASS
              valueFrom:
                secretKeyRef:
                  key: jira_omegaprime_pass
                  name: sync2jira-secret
            - name: SYNC2JIRA_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: github_token
                  name: sync2jira-secret
            - name: CONFLUENCE_SPACE
              value: ${CONFLUENCE_SPACE}
            - name: CONFLUENCE_PAGE_TITLE
              value: ${CONFLUENCE_PAGE_TITLE}
            - name: CONFLUENCE_URL
              value: ${CONFLUENCE_URL}
            - name: CONFLUENCE_USERNAME
              value: sync2jira-confluence
            - name: CONFLUENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: sync2jira-confluence
                  name: sync2jira-secret
            - name: INITILIZE
              value: ${INITILIZE}
        volumes:
          - name: fedmsgd-volume
            configMap:
              name: fedmsgd
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - sync2jira-container
          from:
            kind: ImageStreamTag
            name: sync2jira:latest
      - type: ConfigChange
